<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd67b05f31533b248c40ebbbe7ced556c
{
    public static $files = array (
        '941748b3c8cae4466c827dfb5ca9602a' => __DIR__ . '/..' . '/rmccue/requests/library/Deprecated.php',
    );

    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WpOrg\\Requests\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WpOrg\\Requests\\' => 
        array (
            0 => __DIR__ . '/..' . '/rmccue/requests/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Requests' => __DIR__ . '/..' . '/rmccue/requests/library/Requests.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd67b05f31533b248c40ebbbe7ced556c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd67b05f31533b248c40ebbbe7ced556c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd67b05f31533b248c40ebbbe7ced556c::$classMap;

        }, null, ClassLoader::class);
    }
}
