-- Scientific article wizard: draft storage.
-- Import this in your *article builder* MySQL database (recommended on shared hosting),
-- or in the same database as the main site if $database_article_builder equals $database in lib/sql_connect.php.

CREATE TABLE IF NOT EXISTS `scientific_article_drafts` (
  `draft_id` int UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int UNSIGNED NOT NULL DEFAULT 0,
  `target_web_id` varchar(255) NOT NULL,
  `step` tinyint UNSIGNED NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `title` varchar(512) NOT NULL DEFAULT '',
  `authors` varchar(512) NOT NULL DEFAULT '',
  `problem` text,
  `problem_importance` text,
  `prev_solution_1` text,
  `prev_solution_2` text,
  `prev_solution_3` text,
  `prev_solution_drawback_1` text,
  `prev_solution_drawback_2` text,
  `prev_solution_drawback_3` text,
  `sloution` text,
  `sloution_advantage_1` text,
  `sloution_advantage_2` text,
  `content` mediumtext,
  `keywords` text,
  `ref_authors_1` varchar(512) DEFAULT NULL,
  `ref_article_title_1` varchar(512) DEFAULT NULL,
  `ref_journal_title_1` varchar(512) DEFAULT NULL,
  `ref_vol_issue_1` varchar(255) DEFAULT NULL,
  `ref_authors_2` varchar(512) DEFAULT NULL,
  `ref_article_title_2` varchar(512) DEFAULT NULL,
  `ref_journal_title_2` varchar(512) DEFAULT NULL,
  `ref_vol_issue_2` varchar(255) DEFAULT NULL,
  `ref_authors_3` varchar(512) DEFAULT NULL,
  `ref_article_title_3` varchar(512) DEFAULT NULL,
  `ref_journal_title_3` varchar(512) DEFAULT NULL,
  `ref_vol_issue_3` varchar(255) DEFAULT NULL,
  `related_link_number` int DEFAULT NULL,
  `problem_exp` text,
  `problem_importance_exp` text,
  `prev_solution_drawback_1_exp` text,
  `prev_solution_drawback_2_exp` text,
  `prev_solution_drawback_3_exp` text,
  `sloution_exp` text,
  `sloution_advantage_1_exp` text,
  `sloution_advantage_2_exp` text,
  `keywords_final` text,
  PRIMARY KEY (`draft_id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_web` (`target_web_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
